apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: repo-sync-role
  namespace: prod
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: repo-sync-rolebinding
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: repo-sync-role
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-prod
    namespace: config-management-system
