apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: staging-role
  namespace: staging
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
