apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: staging-rolebinding
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: staging-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: staging
